export const CATEGORIES = {
  Food: {
    label: 'Food & Dining',
    icon: '🍔',
    color: 'orange',
    gradient: 'from-orange-500 to-amber-500',
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    text: 'text-orange-700 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-800',
    bar: 'bg-gradient-to-r from-orange-500 to-amber-400',
    hex: '#f97316',
  },
  Travel: {
    label: 'Travel',
    icon: '✈️',
    color: 'sky',
    gradient: 'from-sky-500 to-blue-500',
    bg: 'bg-sky-50 dark:bg-sky-950/30',
    text: 'text-sky-700 dark:text-sky-400',
    border: 'border-sky-200 dark:border-sky-800',
    bar: 'bg-gradient-to-r from-sky-500 to-blue-400',
    hex: '#0ea5e9',
  },
  Rent: {
    label: 'Rent & Housing',
    icon: '🏠',
    color: 'rose',
    gradient: 'from-rose-500 to-pink-500',
    bg: 'bg-rose-50 dark:bg-rose-950/30',
    text: 'text-rose-700 dark:text-rose-400',
    border: 'border-rose-200 dark:border-rose-800',
    bar: 'bg-gradient-to-r from-rose-500 to-pink-400',
    hex: '#f43f5e',
  },
  Utilities: {
    label: 'Utilities',
    icon: '⚡',
    color: 'yellow',
    gradient: 'from-yellow-500 to-lime-500',
    bg: 'bg-yellow-50 dark:bg-yellow-950/30',
    text: 'text-yellow-700 dark:text-yellow-400',
    border: 'border-yellow-200 dark:border-yellow-800',
    bar: 'bg-gradient-to-r from-yellow-500 to-lime-400',
    hex: '#eab308',
  },
  Entertainment: {
    label: 'Entertainment',
    icon: '🎬',
    color: 'purple',
    gradient: 'from-purple-500 to-violet-500',
    bg: 'bg-purple-50 dark:bg-purple-950/30',
    text: 'text-purple-700 dark:text-purple-400',
    border: 'border-purple-200 dark:border-purple-800',
    bar: 'bg-gradient-to-r from-purple-500 to-violet-400',
    hex: '#a855f7',
  },
  Shopping: {
    label: 'Shopping',
    icon: '🛍️',
    color: 'pink',
    gradient: 'from-pink-500 to-fuchsia-500',
    bg: 'bg-pink-50 dark:bg-pink-950/30',
    text: 'text-pink-700 dark:text-pink-400',
    border: 'border-pink-200 dark:border-pink-800',
    bar: 'bg-gradient-to-r from-pink-500 to-fuchsia-400',
    hex: '#ec4899',
  },
  Health: {
    label: 'Health',
    icon: '🏥',
    color: 'green',
    gradient: 'from-green-500 to-emerald-500',
    bg: 'bg-green-50 dark:bg-green-950/30',
    text: 'text-green-700 dark:text-green-400',
    border: 'border-green-200 dark:border-green-800',
    bar: 'bg-gradient-to-r from-green-500 to-emerald-400',
    hex: '#22c55e',
  },
  Education: {
    label: 'Education',
    icon: '📚',
    color: 'indigo',
    gradient: 'from-indigo-500 to-blue-500',
    bg: 'bg-indigo-50 dark:bg-indigo-950/30',
    text: 'text-indigo-700 dark:text-indigo-400',
    border: 'border-indigo-200 dark:border-indigo-800',
    bar: 'bg-gradient-to-r from-indigo-500 to-blue-400',
    hex: '#6366f1',
  },
  Marketing: {
    label: 'Marketing',
    icon: '📢',
    color: 'teal',
    gradient: 'from-teal-500 to-cyan-500',
    bg: 'bg-teal-50 dark:bg-teal-950/30',
    text: 'text-teal-700 dark:text-teal-400',
    border: 'border-teal-200 dark:border-teal-800',
    bar: 'bg-gradient-to-r from-teal-500 to-cyan-400',
    hex: '#14b8a6',
  },
  Other: {
    label: 'Other',
    icon: '📦',
    color: 'slate',
    gradient: 'from-slate-500 to-gray-500',
    bg: 'bg-slate-50 dark:bg-slate-950/30',
    text: 'text-slate-700 dark:text-slate-400',
    border: 'border-slate-200 dark:border-slate-800',
    bar: 'bg-gradient-to-r from-slate-500 to-gray-400',
    hex: '#64748b',
  },
};

export const CATEGORY_KEYS = Object.keys(CATEGORIES);

export function getCategoryInfo(category) {
  return CATEGORIES[category] || CATEGORIES.Other;
}
